 #Dockerfile para el Frontend React (construcción y servicio con Nginx)

# Etapa de construcción: Crea la aplicación React
FROM node:18-alpine as build-stage
WORKDIR ./
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa de producción: Sirve la aplicación con Nginx
FROM nginx:alpine as production-stage
# Copia los archivos de configuración de Nginx (opcional, pero buena práctica)
# Si necesitas configuración de Nginx personalizada, crea un archivo `nginx.conf`
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
#COPY --from=build-stage ./dist /usr/share/nginx/html
COPY --from=build-stage ./dist /usr/share/nginx/html
# Expone el puerto 80, que es el puerto por defecto de Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]